---@class od.HexColor string

---@class od.GitPalette
---@field public add od.HexColor
---@field public change od.HexColor
---@field public conflict od.HexColor
---@field public delete od.HexColor
---@field public ignore od.HexColor

---@class od.DiffPalette
---@field public add od.HexColor
---@field public delete od.HexColor
---@field public change od.HexColor
---@field public text od.HexColor

---@class od.GitSignPalette
---@field public add od.HexColor
---@field public change od.HexColor
---@field public delete od.HexColor

---@class od.ColorPalette
---@field public none od.HexColor
---@field public bg0 od.HexColor
---@field public bg1 od.HexColor
---@field public bg_highlight od.HexColor
---@field public bg_visual od.HexColor
---@field public black0 od.HexColor
---@field public blue0 od.HexColor
---@field public blue1 od.HexColor
---@field public cyan0 od.HexColor
---@field public fg0 od.HexColor
---@field public fg_dark od.HexColor
---@field public fg_gutter od.HexColor
---@field public fg_light od.HexColor
---@field public green0 od.HexColor
---@field public orange0 od.HexColor
---@field public orange1 od.HexColor
---@field public purple0 od.HexColor
---@field public red0 od.HexColor
---@field public red1 od.HexColor
---@field public red2 od.HexColor
---@field public yellow0 od.HexColor
---@field public yellow1 od.HexColor
---@field public c.git od.GitPalette
---@field public c.diff od.DiffPalette
---@field public c.git_signs od.GitSignPalette
-- Sidebar and Floats
---@field public bg_sidebar od.HexColor
---@field public bg_float od.HexColor
-- EndOfBuffer
---@field public sidebar_eob od.HexColor
---@field public eob od.HexColor
-- LineNumber
---@field public bg_linenumber od.HexColor
-- Search
---@field public bg_search od.HexColor
---@field public fg_search od.HexColor
-- Diagnostic
---@field public error od.HexColor
---@field public warning od.HexColor
---@field public info od.HexColor
---@field public hint od.HexColor
